//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimDemo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Countries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Countries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClaimDemo.Resources.Countries", typeof(Countries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afghanistan.
        /// </summary>
        public static string Afghanistan_SE {
            get {
                return ResourceManager.GetString("Afghanistan_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albanien.
        /// </summary>
        public static string Albania_SE {
            get {
                return ResourceManager.GetString("Albania_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algeriet.
        /// </summary>
        public static string Algeria_SE {
            get {
                return ResourceManager.GetString("Algeria_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andorra.
        /// </summary>
        public static string Andorra_SE {
            get {
                return ResourceManager.GetString("Andorra_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angola.
        /// </summary>
        public static string Angola_SE {
            get {
                return ResourceManager.GetString("Angola_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antigua och Barbuda.
        /// </summary>
        public static string AntiguaAndBarbuda_SE {
            get {
                return ResourceManager.GetString("AntiguaAndBarbuda_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argentina.
        /// </summary>
        public static string Argentina_SE {
            get {
                return ResourceManager.GetString("Argentina_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armenien.
        /// </summary>
        public static string Armenia_SE {
            get {
                return ResourceManager.GetString("Armenia_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australien.
        /// </summary>
        public static string Australia_SE {
            get {
                return ResourceManager.GetString("Australia_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Österrike.
        /// </summary>
        public static string Austria_SE {
            get {
                return ResourceManager.GetString("Austria_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbajdzjan.
        /// </summary>
        public static string Azerbaijan_SE {
            get {
                return ResourceManager.GetString("Azerbaijan_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahamas.
        /// </summary>
        public static string Bahamas_SE {
            get {
                return ResourceManager.GetString("Bahamas_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahrain.
        /// </summary>
        public static string Bahrain_SE {
            get {
                return ResourceManager.GetString("Bahrain_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangladesh.
        /// </summary>
        public static string Bangladesh_SE {
            get {
                return ResourceManager.GetString("Bangladesh_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbados.
        /// </summary>
        public static string Barbados_SE {
            get {
                return ResourceManager.GetString("Barbados_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitryssland.
        /// </summary>
        public static string Belarus_SE {
            get {
                return ResourceManager.GetString("Belarus_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgien.
        /// </summary>
        public static string Belgium_SE {
            get {
                return ResourceManager.GetString("Belgium_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belize.
        /// </summary>
        public static string Belize_SE {
            get {
                return ResourceManager.GetString("Belize_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benin.
        /// </summary>
        public static string Benin_SE {
            get {
                return ResourceManager.GetString("Benin_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bhutan.
        /// </summary>
        public static string Bhutan_SE {
            get {
                return ResourceManager.GetString("Bhutan_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolivia.
        /// </summary>
        public static string Bolivia_SE {
            get {
                return ResourceManager.GetString("Bolivia_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosnien och Hercegovina.
        /// </summary>
        public static string BosniaAndHerzegovina_SE {
            get {
                return ResourceManager.GetString("BosniaAndHerzegovina_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Botswana.
        /// </summary>
        public static string Botswana_SE {
            get {
                return ResourceManager.GetString("Botswana_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brasilien.
        /// </summary>
        public static string Brazil_SE {
            get {
                return ResourceManager.GetString("Brazil_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brunei.
        /// </summary>
        public static string Brunei_SE {
            get {
                return ResourceManager.GetString("Brunei_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgarien.
        /// </summary>
        public static string Bulgaria_SE {
            get {
                return ResourceManager.GetString("Bulgaria_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burkina Faso.
        /// </summary>
        public static string BurkinaFaso_SE {
            get {
                return ResourceManager.GetString("BurkinaFaso_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burundi.
        /// </summary>
        public static string Burundi_SE {
            get {
                return ResourceManager.GetString("Burundi_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kap Verde.
        /// </summary>
        public static string CaboVerde_SE {
            get {
                return ResourceManager.GetString("CaboVerde_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kambodja.
        /// </summary>
        public static string Cambodia_SE {
            get {
                return ResourceManager.GetString("Cambodia_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamerun.
        /// </summary>
        public static string Cameroon_SE {
            get {
                return ResourceManager.GetString("Cameroon_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanada.
        /// </summary>
        public static string Canada_SE {
            get {
                return ResourceManager.GetString("Canada_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centralafrikanska republiken.
        /// </summary>
        public static string CentralAfricanRepublic_SE {
            get {
                return ResourceManager.GetString("CentralAfricanRepublic_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tchad.
        /// </summary>
        public static string Chad_SE {
            get {
                return ResourceManager.GetString("Chad_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chile.
        /// </summary>
        public static string Chile_SE {
            get {
                return ResourceManager.GetString("Chile_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kina.
        /// </summary>
        public static string China_SE {
            get {
                return ResourceManager.GetString("China_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombia.
        /// </summary>
        public static string Colombia_SE {
            get {
                return ResourceManager.GetString("Colombia_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komorerna.
        /// </summary>
        public static string Comoros_SE {
            get {
                return ResourceManager.GetString("Comoros_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kongo.
        /// </summary>
        public static string Congo_SE {
            get {
                return ResourceManager.GetString("Congo_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costa Rica.
        /// </summary>
        public static string CostaRica_SE {
            get {
                return ResourceManager.GetString("CostaRica_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kroatien.
        /// </summary>
        public static string Croatia_SE {
            get {
                return ResourceManager.GetString("Croatia_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuba.
        /// </summary>
        public static string Cuba_SE {
            get {
                return ResourceManager.GetString("Cuba_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cypern.
        /// </summary>
        public static string Cyprus_SE {
            get {
                return ResourceManager.GetString("Cyprus_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tjeckien.
        /// </summary>
        public static string CzechRepublic_SE {
            get {
                return ResourceManager.GetString("CzechRepublic_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danmark.
        /// </summary>
        public static string Denmark_SE {
            get {
                return ResourceManager.GetString("Denmark_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Djibouti.
        /// </summary>
        public static string Djibouti_SE {
            get {
                return ResourceManager.GetString("Djibouti_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominica.
        /// </summary>
        public static string Dominica_SE {
            get {
                return ResourceManager.GetString("Dominica_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominikanska republiken.
        /// </summary>
        public static string DominicanRepublic_SE {
            get {
                return ResourceManager.GetString("DominicanRepublic_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Östtimor.
        /// </summary>
        public static string EastTimor_SE {
            get {
                return ResourceManager.GetString("EastTimor_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekvador.
        /// </summary>
        public static string Ecuador_SE {
            get {
                return ResourceManager.GetString("Ecuador_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egypten.
        /// </summary>
        public static string Egypt_SE {
            get {
                return ResourceManager.GetString("Egypt_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Salvador.
        /// </summary>
        public static string ElSalvador_SE {
            get {
                return ResourceManager.GetString("ElSalvador_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekvatorialguinea.
        /// </summary>
        public static string EquatorialGuinea_SE {
            get {
                return ResourceManager.GetString("EquatorialGuinea_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eritrea.
        /// </summary>
        public static string Eritrea_SE {
            get {
                return ResourceManager.GetString("Eritrea_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estland.
        /// </summary>
        public static string Estonia_SE {
            get {
                return ResourceManager.GetString("Estonia_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eswatini.
        /// </summary>
        public static string Eswatini_SE {
            get {
                return ResourceManager.GetString("Eswatini_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiopien.
        /// </summary>
        public static string Ethiopia_SE {
            get {
                return ResourceManager.GetString("Ethiopia_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiji.
        /// </summary>
        public static string Fiji_SE {
            get {
                return ResourceManager.GetString("Fiji_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finland.
        /// </summary>
        public static string Finland_SE {
            get {
                return ResourceManager.GetString("Finland_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frankrike.
        /// </summary>
        public static string France_SE {
            get {
                return ResourceManager.GetString("France_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gabon.
        /// </summary>
        public static string Gabon_SE {
            get {
                return ResourceManager.GetString("Gabon_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gambia.
        /// </summary>
        public static string Gambia_SE {
            get {
                return ResourceManager.GetString("Gambia_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgien.
        /// </summary>
        public static string Georgia_SE {
            get {
                return ResourceManager.GetString("Georgia_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tyskland.
        /// </summary>
        public static string Germany_SE {
            get {
                return ResourceManager.GetString("Germany_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghana.
        /// </summary>
        public static string Ghana_SE {
            get {
                return ResourceManager.GetString("Ghana_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grekland.
        /// </summary>
        public static string Greece_SE {
            get {
                return ResourceManager.GetString("Greece_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grenada.
        /// </summary>
        public static string Grenada_SE {
            get {
                return ResourceManager.GetString("Grenada_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guatemala.
        /// </summary>
        public static string Guatemala_SE {
            get {
                return ResourceManager.GetString("Guatemala_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guinea.
        /// </summary>
        public static string Guinea_SE {
            get {
                return ResourceManager.GetString("Guinea_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guinea-Bissau.
        /// </summary>
        public static string GuineaBissau_SE {
            get {
                return ResourceManager.GetString("GuineaBissau_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guyana.
        /// </summary>
        public static string Guyana_SE {
            get {
                return ResourceManager.GetString("Guyana_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haiti.
        /// </summary>
        public static string Haiti_SE {
            get {
                return ResourceManager.GetString("Haiti_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honduras.
        /// </summary>
        public static string Honduras_SE {
            get {
                return ResourceManager.GetString("Honduras_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungern.
        /// </summary>
        public static string Hungary_SE {
            get {
                return ResourceManager.GetString("Hungary_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Island.
        /// </summary>
        public static string Iceland_SE {
            get {
                return ResourceManager.GetString("Iceland_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indien.
        /// </summary>
        public static string India_SE {
            get {
                return ResourceManager.GetString("India_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonesien.
        /// </summary>
        public static string Indonesia_SE {
            get {
                return ResourceManager.GetString("Indonesia_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran.
        /// </summary>
        public static string Iran_SE {
            get {
                return ResourceManager.GetString("Iran_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irak.
        /// </summary>
        public static string Iraq_SE {
            get {
                return ResourceManager.GetString("Iraq_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irland.
        /// </summary>
        public static string Ireland_SE {
            get {
                return ResourceManager.GetString("Ireland_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Israel.
        /// </summary>
        public static string Israel_SE {
            get {
                return ResourceManager.GetString("Israel_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italien.
        /// </summary>
        public static string Italy_SE {
            get {
                return ResourceManager.GetString("Italy_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elfenbenskusten.
        /// </summary>
        public static string IvoryCoast_SE {
            get {
                return ResourceManager.GetString("IvoryCoast_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jamaica.
        /// </summary>
        public static string Jamaica_SE {
            get {
                return ResourceManager.GetString("Jamaica_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japan.
        /// </summary>
        public static string Japan_SE {
            get {
                return ResourceManager.GetString("Japan_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jordanien.
        /// </summary>
        public static string Jordan_SE {
            get {
                return ResourceManager.GetString("Jordan_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kasakhstan.
        /// </summary>
        public static string Kazakhstan_SE {
            get {
                return ResourceManager.GetString("Kazakhstan_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kenya.
        /// </summary>
        public static string Kenya_SE {
            get {
                return ResourceManager.GetString("Kenya_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiribati.
        /// </summary>
        public static string Kiribati_SE {
            get {
                return ResourceManager.GetString("Kiribati_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nordkorea.
        /// </summary>
        public static string KoreaNorth_SE {
            get {
                return ResourceManager.GetString("KoreaNorth_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sydkorea.
        /// </summary>
        public static string KoreaSouth_SE {
            get {
                return ResourceManager.GetString("KoreaSouth_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kosovo.
        /// </summary>
        public static string Kosovo_SE {
            get {
                return ResourceManager.GetString("Kosovo_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuwait.
        /// </summary>
        public static string Kuwait_SE {
            get {
                return ResourceManager.GetString("Kuwait_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirgizistan.
        /// </summary>
        public static string Kyrgyzstan_SE {
            get {
                return ResourceManager.GetString("Kyrgyzstan_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laos.
        /// </summary>
        public static string Laos_SE {
            get {
                return ResourceManager.GetString("Laos_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lettland.
        /// </summary>
        public static string Latvia_SE {
            get {
                return ResourceManager.GetString("Latvia_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libanon.
        /// </summary>
        public static string Lebanon_SE {
            get {
                return ResourceManager.GetString("Lebanon_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesotho.
        /// </summary>
        public static string Lesotho_SE {
            get {
                return ResourceManager.GetString("Lesotho_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liberia.
        /// </summary>
        public static string Liberia_SE {
            get {
                return ResourceManager.GetString("Liberia_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libyen.
        /// </summary>
        public static string Libya_SE {
            get {
                return ResourceManager.GetString("Libya_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liechtenstein.
        /// </summary>
        public static string Liechtenstein_SE {
            get {
                return ResourceManager.GetString("Liechtenstein_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Litauen.
        /// </summary>
        public static string Lithuania_SE {
            get {
                return ResourceManager.GetString("Lithuania_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxemburg.
        /// </summary>
        public static string Luxembourg_SE {
            get {
                return ResourceManager.GetString("Luxembourg_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Madagaskar.
        /// </summary>
        public static string Madagascar_SE {
            get {
                return ResourceManager.GetString("Madagascar_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malawi.
        /// </summary>
        public static string Malawi_SE {
            get {
                return ResourceManager.GetString("Malawi_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malaysia.
        /// </summary>
        public static string Malaysia_SE {
            get {
                return ResourceManager.GetString("Malaysia_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maldiverna.
        /// </summary>
        public static string Maldives_SE {
            get {
                return ResourceManager.GetString("Maldives_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mali.
        /// </summary>
        public static string Mali_SE {
            get {
                return ResourceManager.GetString("Mali_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malta.
        /// </summary>
        public static string Malta_SE {
            get {
                return ResourceManager.GetString("Malta_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marshallöarna.
        /// </summary>
        public static string MarshallIslands_SE {
            get {
                return ResourceManager.GetString("MarshallIslands_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauretanien.
        /// </summary>
        public static string Mauritania_SE {
            get {
                return ResourceManager.GetString("Mauritania_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauritius.
        /// </summary>
        public static string Mauritius_SE {
            get {
                return ResourceManager.GetString("Mauritius_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexiko.
        /// </summary>
        public static string Mexico_SE {
            get {
                return ResourceManager.GetString("Mexico_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mikronesien.
        /// </summary>
        public static string Micronesia_SE {
            get {
                return ResourceManager.GetString("Micronesia_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moldavien.
        /// </summary>
        public static string Moldova_SE {
            get {
                return ResourceManager.GetString("Moldova_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monaco.
        /// </summary>
        public static string Monaco_SE {
            get {
                return ResourceManager.GetString("Monaco_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mongoliet.
        /// </summary>
        public static string Mongolia_SE {
            get {
                return ResourceManager.GetString("Mongolia_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montenegro.
        /// </summary>
        public static string Montenegro_SE {
            get {
                return ResourceManager.GetString("Montenegro_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marocko.
        /// </summary>
        public static string Morocco_SE {
            get {
                return ResourceManager.GetString("Morocco_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moçambique.
        /// </summary>
        public static string Mozambique_SE {
            get {
                return ResourceManager.GetString("Mozambique_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Myanmar.
        /// </summary>
        public static string Myanmar_SE {
            get {
                return ResourceManager.GetString("Myanmar_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namibia.
        /// </summary>
        public static string Namibia_SE {
            get {
                return ResourceManager.GetString("Namibia_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nauru.
        /// </summary>
        public static string Nauru_SE {
            get {
                return ResourceManager.GetString("Nauru_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepal.
        /// </summary>
        public static string Nepal_SE {
            get {
                return ResourceManager.GetString("Nepal_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nederländerna.
        /// </summary>
        public static string Netherlands_SE {
            get {
                return ResourceManager.GetString("Netherlands_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nya Zeeland.
        /// </summary>
        public static string NewZealand_SE {
            get {
                return ResourceManager.GetString("NewZealand_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicaragua.
        /// </summary>
        public static string Nicaragua_SE {
            get {
                return ResourceManager.GetString("Nicaragua_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niger.
        /// </summary>
        public static string Niger_SE {
            get {
                return ResourceManager.GetString("Niger_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nigeria.
        /// </summary>
        public static string Nigeria_SE {
            get {
                return ResourceManager.GetString("Nigeria_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nordmakedonien.
        /// </summary>
        public static string NorthMacedonia_SE {
            get {
                return ResourceManager.GetString("NorthMacedonia_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norge.
        /// </summary>
        public static string Norway_SE {
            get {
                return ResourceManager.GetString("Norway_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oman.
        /// </summary>
        public static string Oman_SE {
            get {
                return ResourceManager.GetString("Oman_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pakistan.
        /// </summary>
        public static string Pakistan_SE {
            get {
                return ResourceManager.GetString("Pakistan_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palau.
        /// </summary>
        public static string Palau_SE {
            get {
                return ResourceManager.GetString("Palau_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stat Palestina.
        /// </summary>
        public static string Palestine_SE {
            get {
                return ResourceManager.GetString("Palestine_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panama.
        /// </summary>
        public static string Panama_SE {
            get {
                return ResourceManager.GetString("Panama_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papua Nya Guinea.
        /// </summary>
        public static string PapuaNewGuinea_SE {
            get {
                return ResourceManager.GetString("PapuaNewGuinea_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paraguay.
        /// </summary>
        public static string Paraguay_SE {
            get {
                return ResourceManager.GetString("Paraguay_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peru.
        /// </summary>
        public static string Peru_SE {
            get {
                return ResourceManager.GetString("Peru_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filippinerna.
        /// </summary>
        public static string Philippines_SE {
            get {
                return ResourceManager.GetString("Philippines_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polen.
        /// </summary>
        public static string Poland_SE {
            get {
                return ResourceManager.GetString("Poland_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portugal.
        /// </summary>
        public static string Portugal_SE {
            get {
                return ResourceManager.GetString("Portugal_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qatar.
        /// </summary>
        public static string Qatar_SE {
            get {
                return ResourceManager.GetString("Qatar_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rumänien.
        /// </summary>
        public static string Romania_SE {
            get {
                return ResourceManager.GetString("Romania_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ryssland.
        /// </summary>
        public static string Russia_SE {
            get {
                return ResourceManager.GetString("Russia_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rwanda.
        /// </summary>
        public static string Rwanda_SE {
            get {
                return ResourceManager.GetString("Rwanda_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint Kitts och Nevis.
        /// </summary>
        public static string SaintKittsAndNevis_SE {
            get {
                return ResourceManager.GetString("SaintKittsAndNevis_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint Lucia.
        /// </summary>
        public static string SaintLucia_SE {
            get {
                return ResourceManager.GetString("SaintLucia_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint Vincent och Grenadinerna.
        /// </summary>
        public static string SaintVincentAndTheGrenadines_SE {
            get {
                return ResourceManager.GetString("SaintVincentAndTheGrenadines_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samoa.
        /// </summary>
        public static string Samoa_SE {
            get {
                return ResourceManager.GetString("Samoa_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to San Marino.
        /// </summary>
        public static string SanMarino_SE {
            get {
                return ResourceManager.GetString("SanMarino_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sao Tome och Principe.
        /// </summary>
        public static string SaoTomeAndPrincipe_SE {
            get {
                return ResourceManager.GetString("SaoTomeAndPrincipe_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saudiarabien.
        /// </summary>
        public static string SaudiArabia_SE {
            get {
                return ResourceManager.GetString("SaudiArabia_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senegal.
        /// </summary>
        public static string Senegal_SE {
            get {
                return ResourceManager.GetString("Senegal_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbien.
        /// </summary>
        public static string Serbia_SE {
            get {
                return ResourceManager.GetString("Serbia_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seychellerna.
        /// </summary>
        public static string Seychelles_SE {
            get {
                return ResourceManager.GetString("Seychelles_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sierra Leone.
        /// </summary>
        public static string SierraLeone_SE {
            get {
                return ResourceManager.GetString("SierraLeone_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singapore.
        /// </summary>
        public static string Singapore_SE {
            get {
                return ResourceManager.GetString("Singapore_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovakien.
        /// </summary>
        public static string Slovakia_SE {
            get {
                return ResourceManager.GetString("Slovakia_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovenien.
        /// </summary>
        public static string Slovenia_SE {
            get {
                return ResourceManager.GetString("Slovenia_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salomonöarna.
        /// </summary>
        public static string SolomonIslands_SE {
            get {
                return ResourceManager.GetString("SolomonIslands_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somalia.
        /// </summary>
        public static string Somalia_SE {
            get {
                return ResourceManager.GetString("Somalia_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sydafrika.
        /// </summary>
        public static string SouthAfrica_SE {
            get {
                return ResourceManager.GetString("SouthAfrica_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sydsudan.
        /// </summary>
        public static string SouthSudan_SE {
            get {
                return ResourceManager.GetString("SouthSudan_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanien.
        /// </summary>
        public static string Spain_SE {
            get {
                return ResourceManager.GetString("Spain_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sri Lanka.
        /// </summary>
        public static string SriLanka_SE {
            get {
                return ResourceManager.GetString("SriLanka_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudan.
        /// </summary>
        public static string Sudan_SE {
            get {
                return ResourceManager.GetString("Sudan_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surinam.
        /// </summary>
        public static string Suriname_SE {
            get {
                return ResourceManager.GetString("Suriname_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sverige.
        /// </summary>
        public static string Sweden_SE {
            get {
                return ResourceManager.GetString("Sweden_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schweiz.
        /// </summary>
        public static string Switzerland_SE {
            get {
                return ResourceManager.GetString("Switzerland_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thailand.
        /// </summary>
        public static string Thailand_SE {
            get {
                return ResourceManager.GetString("Thailand_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storbritannien.
        /// </summary>
        public static string UnitedKingdom_SE {
            get {
                return ResourceManager.GetString("UnitedKingdom_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA.
        /// </summary>
        public static string UnitedStates_SE {
            get {
                return ResourceManager.GetString("UnitedStates_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uruguay.
        /// </summary>
        public static string Uruguay_SE {
            get {
                return ResourceManager.GetString("Uruguay_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usbekistan.
        /// </summary>
        public static string Uzbekistan_SE {
            get {
                return ResourceManager.GetString("Uzbekistan_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanuatu.
        /// </summary>
        public static string Vanuatu_SE {
            get {
                return ResourceManager.GetString("Vanuatu_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaticanstaten.
        /// </summary>
        public static string VaticanCity_SE {
            get {
                return ResourceManager.GetString("VaticanCity_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venezuela.
        /// </summary>
        public static string Venezuela_SE {
            get {
                return ResourceManager.GetString("Venezuela_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnam.
        /// </summary>
        public static string Vietnam_SE {
            get {
                return ResourceManager.GetString("Vietnam_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jemen.
        /// </summary>
        public static string Yemen_SE {
            get {
                return ResourceManager.GetString("Yemen_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zambia.
        /// </summary>
        public static string Zambia_SE {
            get {
                return ResourceManager.GetString("Zambia_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zimbabwe.
        /// </summary>
        public static string Zimbabwe_SE {
            get {
                return ResourceManager.GetString("Zimbabwe_SE", resourceCulture);
            }
        }
    }
}
