//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimDemo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClaimDemo.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress saknas..
        /// </summary>
        public static string ErrorMessage_AddressMissing_SE {
            get {
                return ResourceManager.GetString("ErrorMessage_AddressMissing_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land saknas..
        /// </summary>
        public static string ErrorMessage_CountryMissing_SE {
            get {
                return ResourceManager.GetString("ErrorMessage_CountryMissing_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beskrivning saknas..
        /// </summary>
        public static string ErrorMessage_DescriptionMissing_SE {
            get {
                return ResourceManager.GetString("ErrorMessage_DescriptionMissing_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beskriviningen måste minst vara 20 karaktärer långt..
        /// </summary>
        public static string ErrorMessage_DescriptionTooShort_SE {
            get {
                return ResourceManager.GetString("ErrorMessage_DescriptionTooShort_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slutdatum måste vara samma som eller efter startdatum..
        /// </summary>
        public static string ErrorMessage_EndDateBeforeStartDate_SE {
            get {
                return ResourceManager.GetString("ErrorMessage_EndDateBeforeStartDate_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slutdatum saknas..
        /// </summary>
        public static string ErrorMessage_EndDateMissing_SE {
            get {
                return ResourceManager.GetString("ErrorMessage_EndDateMissing_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Uppskattad konstant måste vara över 0kr..
        /// </summary>
        public static string ErrorMessage_EstimatedDamageCostZero_SE {
            get {
                return ResourceManager.GetString("ErrorMessage_EstimatedDamageCostZero_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skadetillfälle Saknas..
        /// </summary>
        public static string ErrorMessage_MissingReportedDate_SE {
            get {
                return ResourceManager.GetString("ErrorMessage_MissingReportedDate_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fel Registreringsnummerformat, Accepterat format är ABC123 eller ABC12D..
        /// </summary>
        public static string ErrorMessage_RegistrationNumberFormat_SE {
            get {
                return ResourceManager.GetString("ErrorMessage_RegistrationNumberFormat_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registreringsnummer saknas..
        /// </summary>
        public static string ErrorMessage_RegistrationNumberMissing_SE {
            get {
                return ResourceManager.GetString("ErrorMessage_RegistrationNumberMissing_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skadtillfället kan max gå tillbaka 365 dagar..
        /// </summary>
        public static string ErrorMessage_ReportedDateRange_SE {
            get {
                return ResourceManager.GetString("ErrorMessage_ReportedDateRange_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reseskadan måste rapporteras inom 14 dagar efter hemkomst..
        /// </summary>
        public static string ErrorMessage_ReportedTooLate_SE {
            get {
                return ResourceManager.GetString("ErrorMessage_ReportedTooLate_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startdatum saknas..
        /// </summary>
        public static string ErrorMessage_StartDateMissing_SE {
            get {
                return ResourceManager.GetString("ErrorMessage_StartDateMissing_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ av incident saknas..
        /// </summary>
        public static string ErrorMessage_TypeOfIncidentMissing_SE {
            get {
                return ResourceManager.GetString("ErrorMessage_TypeOfIncidentMissing_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ av egendomsskada saknas..
        /// </summary>
        public static string ErrorMessage_TypeOfPropertyDamageMissing_SE {
            get {
                return ResourceManager.GetString("ErrorMessage_TypeOfPropertyDamageMissing_SE", resourceCulture);
            }
        }
    }
}
