//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimDemo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClaimDemo.Resources.ResourceStrings", typeof(ResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redigera.
        /// </summary>
        public static string ClaimDetail_EditButton_SE {
            get {
                return ResourceManager.GetString("ClaimDetail_EditButton_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uppdatera.
        /// </summary>
        public static string ClaimDetail_UpdateButton_SE {
            get {
                return ResourceManager.GetString("ClaimDetail_UpdateButton_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaljer.
        /// </summary>
        public static string ClaimList_Actions_SE {
            get {
                return ResourceManager.GetString("ClaimList_Actions_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress:.
        /// </summary>
        public static string ClaimList_Address_SE {
            get {
                return ResourceManager.GetString("ClaimList_Address_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alla typer.
        /// </summary>
        public static string ClaimList_AllTypes_SE {
            get {
                return ResourceManager.GetString("ClaimList_AllTypes_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land:.
        /// </summary>
        public static string ClaimList_Country_SE {
            get {
                return ResourceManager.GetString("ClaimList_Country_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skadetyp:.
        /// </summary>
        public static string ClaimList_DamageType_SE {
            get {
                return ResourceManager.GetString("ClaimList_DamageType_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beskrivning:.
        /// </summary>
        public static string ClaimList_Description_SE {
            get {
                return ResourceManager.GetString("ClaimList_Description_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slutdatum:.
        /// </summary>
        public static string ClaimList_EndDate_SE {
            get {
                return ResourceManager.GetString("ClaimList_EndDate_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrera.
        /// </summary>
        public static string ClaimList_FilterButton_SE {
            get {
                return ResourceManager.GetString("ClaimList_FilterButton_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Från datum.
        /// </summary>
        public static string ClaimList_FilterDateFrom_SE {
            get {
                return ResourceManager.GetString("ClaimList_FilterDateFrom_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Till datum.
        /// </summary>
        public static string ClaimList_FilterDateTo_SE {
            get {
                return ResourceManager.GetString("ClaimList_FilterDateTo_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrera på typ.
        /// </summary>
        public static string ClaimList_FilterType_SE {
            get {
                return ResourceManager.GetString("ClaimList_FilterType_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tillbaka till listan.
        /// </summary>
        public static string ClaimList_GoBack_SE {
            get {
                return ResourceManager.GetString("ClaimList_GoBack_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dölj detaljer.
        /// </summary>
        public static string ClaimList_HideDetails_SE {
            get {
                return ResourceManager.GetString("ClaimList_HideDetails_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string ClaimList_ID_SE {
            get {
                return ResourceManager.GetString("ClaimList_ID_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Händelsetyp:.
        /// </summary>
        public static string ClaimList_IncidentType_SE {
            get {
                return ResourceManager.GetString("ClaimList_IncidentType_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laddar....
        /// </summary>
        public static string ClaimList_Loading_SE {
            get {
                return ResourceManager.GetString("ClaimList_Loading_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inga skador hittades..
        /// </summary>
        public static string ClaimList_NoClaims_SE {
            get {
                return ResourceManager.GetString("ClaimList_NoClaims_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registreringsnummer:.
        /// </summary>
        public static string ClaimList_RegistrationNumber_SE {
            get {
                return ResourceManager.GetString("ClaimList_RegistrationNumber_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmälningsdatum.
        /// </summary>
        public static string ClaimList_ReportedDate_SE {
            get {
                return ResourceManager.GetString("ClaimList_ReportedDate_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Återställ.
        /// </summary>
        public static string ClaimList_ResetButton_SE {
            get {
                return ResourceManager.GetString("ClaimList_ResetButton_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa detaljer.
        /// </summary>
        public static string ClaimList_ShowDetails_SE {
            get {
                return ResourceManager.GetString("ClaimList_ShowDetails_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stigande.
        /// </summary>
        public static string ClaimList_SortAsc_SE {
            get {
                return ResourceManager.GetString("ClaimList_SortAsc_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortera efter.
        /// </summary>
        public static string ClaimList_SortBy_SE {
            get {
                return ResourceManager.GetString("ClaimList_SortBy_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallande.
        /// </summary>
        public static string ClaimList_SortDesc_SE {
            get {
                return ResourceManager.GetString("ClaimList_SortDesc_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startdatum:.
        /// </summary>
        public static string ClaimList_StartDate_SE {
            get {
                return ResourceManager.GetString("ClaimList_StartDate_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skador.
        /// </summary>
        public static string ClaimList_Title_SE {
            get {
                return ResourceManager.GetString("ClaimList_Title_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ.
        /// </summary>
        public static string ClaimList_Type_SE {
            get {
                return ResourceManager.GetString("ClaimList_Type_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eskalerad.
        /// </summary>
        public static string ClaimStatus_Escalated_SE {
            get {
                return ResourceManager.GetString("ClaimStatus_Escalated_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedrägerikontroll.
        /// </summary>
        public static string ClaimStatus_FraudCheck_SE {
            get {
                return ResourceManager.GetString("ClaimStatus_FraudCheck_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen.
        /// </summary>
        public static string ClaimStatus_None_SE {
            get {
                return ResourceManager.GetString("ClaimStatus_None_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kräver manuell granskning.
        /// </summary>
        public static string ClaimStatus_RequiresManualReview_SE {
            get {
                return ResourceManager.GetString("ClaimStatus_RequiresManualReview_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen.
        /// </summary>
        public static string ClaimType_None_SE {
            get {
                return ResourceManager.GetString("ClaimType_None_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egendom.
        /// </summary>
        public static string ClaimType_Property_SE {
            get {
                return ResourceManager.GetString("ClaimType_Property_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resa.
        /// </summary>
        public static string ClaimType_Travel_SE {
            get {
                return ResourceManager.GetString("ClaimType_Travel_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fordon.
        /// </summary>
        public static string ClaimType_Vehicle_SE {
            get {
                return ResourceManager.GetString("ClaimType_Vehicle_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ av skada:.
        /// </summary>
        public static string ClaimTypeLabel_SE {
            get {
                return ResourceManager.GetString("ClaimTypeLabel_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avbryt.
        /// </summary>
        public static string ConfirmDialog_CancelButton_SE {
            get {
                return ResourceManager.GetString("ConfirmDialog_CancelButton_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort.
        /// </summary>
        public static string ConfirmDialog_ConfirmButton_SE {
            get {
                return ResourceManager.GetString("ConfirmDialog_ConfirmButton_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Är du säker på att du vill ta bort denna skadeanmälan?.
        /// </summary>
        public static string ConfirmDialog_Message_SE {
            get {
                return ResourceManager.GetString("ConfirmDialog_Message_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekräfta borttagning.
        /// </summary>
        public static string ConfirmDialog_Title_SE {
            get {
                return ResourceManager.GetString("ConfirmDialog_Title_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land:.
        /// </summary>
        public static string CountryLabel_SE {
            get {
                return ResourceManager.GetString("CountryLabel_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa skadeanmälan.
        /// </summary>
        public static string CreateClaim_SE {
            get {
                return ResourceManager.GetString("CreateClaim_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skadeanmälan har skickats!.
        /// </summary>
        public static string CreatedClaim_SuccessMessage_SE {
            get {
                return ResourceManager.GetString("CreatedClaim_SuccessMessage_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skadeanmälan är borttagen!.
        /// </summary>
        public static string DeleteClaim_SuccessMessage_SE {
            get {
                return ResourceManager.GetString("DeleteClaim_SuccessMessage_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beskrivning:.
        /// </summary>
        public static string DescriptionLabel_SE {
            get {
                return ResourceManager.GetString("DescriptionLabel_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slutdatum:.
        /// </summary>
        public static string EndDateLabel_SE {
            get {
                return ResourceManager.GetString("EndDateLabel_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel uppstod: {0}.
        /// </summary>
        public static string ErrorMessage_SE {
            get {
                return ResourceManager.GetString("ErrorMessage_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uppskattad kostnad: .
        /// </summary>
        public static string Estimated_Cost_SE {
            get {
                return ResourceManager.GetString("Estimated_Cost_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olycka.
        /// </summary>
        public static string IncidentType_Accident_SE {
            get {
                return ResourceManager.GetString("IncidentType_Accident_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avbokning.
        /// </summary>
        public static string IncidentType_Cancellation_SE {
            get {
                return ResourceManager.GetString("IncidentType_Cancellation_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Försening.
        /// </summary>
        public static string IncidentType_Delay_SE {
            get {
                return ResourceManager.GetString("IncidentType_Delay_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Förlorat bagage.
        /// </summary>
        public static string IncidentType_LostLuggage_SE {
            get {
                return ResourceManager.GetString("IncidentType_LostLuggage_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicinsk.
        /// </summary>
        public static string IncidentType_Medical_SE {
            get {
                return ResourceManager.GetString("IncidentType_Medical_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annat.
        /// </summary>
        public static string IncidentType_Other_SE {
            get {
                return ResourceManager.GetString("IncidentType_Other_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stöld.
        /// </summary>
        public static string IncidentType_Theft_SE {
            get {
                return ResourceManager.GetString("IncidentType_Theft_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ av incident:.
        /// </summary>
        public static string IncidentTypeLabel_SE {
            get {
                return ResourceManager.GetString("IncidentTypeLabel_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olycksplats:.
        /// </summary>
        public static string PlaceOfAccidentLabel_SE {
            get {
                return ResourceManager.GetString("PlaceOfAccidentLabel_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress:.
        /// </summary>
        public static string PropertyAddressLabel_SE {
            get {
                return ResourceManager.GetString("PropertyAddressLabel_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eld.
        /// </summary>
        public static string PropertyDamageType_Fire_SE {
            get {
                return ResourceManager.GetString("PropertyDamageType_Fire_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stöld.
        /// </summary>
        public static string PropertyDamageType_Theft_SE {
            get {
                return ResourceManager.GetString("PropertyDamageType_Theft_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vatten.
        /// </summary>
        public static string PropertyDamageType_Water_SE {
            get {
                return ResourceManager.GetString("PropertyDamageType_Water_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ av egendomsskada.
        /// </summary>
        public static string PropertyDamageTypeLabel_SE {
            get {
                return ResourceManager.GetString("PropertyDamageTypeLabel_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skadetillfälle:.
        /// </summary>
        public static string ReportedDateLabel_SE {
            get {
                return ResourceManager.GetString("ReportedDateLabel_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Välj land --.
        /// </summary>
        public static string SelectCountryOption_SE {
            get {
                return ResourceManager.GetString("SelectCountryOption_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Välj typ --.
        /// </summary>
        public static string SelectDamageTypeOption_SE {
            get {
                return ResourceManager.GetString("SelectDamageTypeOption_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Välj typ --.
        /// </summary>
        public static string SelectIncidentTypeOption_SE {
            get {
                return ResourceManager.GetString("SelectIncidentTypeOption_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Välj typ --.
        /// </summary>
        public static string SelectTypeOption_SE {
            get {
                return ResourceManager.GetString("SelectTypeOption_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startdatum:.
        /// </summary>
        public static string StartDateLabel_SE {
            get {
                return ResourceManager.GetString("StartDateLabel_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skadeanmälan har uppdaterats!.
        /// </summary>
        public static string UpdatedClaim_SuccessMessage_SE {
            get {
                return ResourceManager.GetString("UpdatedClaim_SuccessMessage_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registreringsnummer:.
        /// </summary>
        public static string VehicleRegistrationLabel_SE {
            get {
                return ResourceManager.GetString("VehicleRegistrationLabel_SE", resourceCulture);
            }
        }
    }
}
